# Generated by Django 5.2.5 on 2025-08-28 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('raised_by', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Regular', 'Regular')], max_length=20)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('via', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('Direct', 'Direct')], max_length=20)),
                ('issue_details', models.TextField()),
                ('responsible_party', models.CharField(choices=[('Logic', 'Logic'), ('MIS', 'MIS')], max_length=10)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('gms_status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('issue_raise_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('comment_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('inserted_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inserted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inserted_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
