# Generated by Django 5.2.5 on 2025-09-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
