# Generated by Django 5.2.5 on 2025-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='crm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
