# Generated by Django 5.2.5 on 2025-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_module_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='users', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(related_name='users', to='accounts.module'),
        ),
    ]
